INFO: Default loss without VGG
INFO: No cutoff
INFO: 2023-08-21 13:37:05 Argument batch_size: 8
INFO: 2023-08-21 13:37:05 Argument code_test: True
INFO: 2023-08-21 13:37:05 Argument data_train_path: ./../data/data_96/train/
INFO: 2023-08-21 13:37:05 Argument data_val_path: ./..data/data_96/val/data_val_chr19_96.npy
INFO: 2023-08-21 13:37:05 Argument device_number: 1
INFO: 2023-08-21 13:37:05 Argument epoch: 1
INFO: 2023-08-21 13:37:05 Argument local_rank: 0
INFO: 2023-08-21 13:37:05 Argument loss: single_channel_no_vgg
INFO: 2023-08-21 13:37:05 Argument max_HiC: 255
INFO: 2023-08-21 13:37:05 Argument num_gpu: 1
INFO: 2023-08-21 13:37:05 Argument num_workers: 1
INFO: 2023-08-21 13:37:05 Argument patch_size: 96
INFO: 2023-08-21 13:37:05 Argument resume_epoch: 0
INFO: 2023-08-21 13:37:05 Argument resume_path: None
INFO: 2023-08-21 13:37:05 Argument rgb: False
INFO: 2023-08-21 13:37:05 Argument train_dataset: hic
INFO: 2023-08-21 13:37:05 Argument val_datasets: ['hic']
INFO: Traceback:
INFO: Traceback (most recent call last):
  File "./train_1d.py", line 314, in <module>
    train(model, args)
  File "./train_1d.py", line 178, in train
    loss_avg = model.train(data_gpu, learning_rate)
  File "/home/dmitryp/dpinchuk/dmvfn/CVPR2023-DMVFN/model/model_1d.py", line 69, in train
    if loss == 'single_channel_no_vgg':
NameError: name 'loss' is not defined

INFO: Sys.exc_info()[2]:
INFO: <traceback object at 0x7fb485423200>
