INFO: Default loss without VGG
INFO: No cutoff
INFO: 2023-08-21 13:56:33 Argument batch_size: 8
INFO: 2023-08-21 13:56:33 Argument code_test: True
INFO: 2023-08-21 13:56:33 Argument data_train_path: ./../data/data_96/train/
INFO: 2023-08-21 13:56:33 Argument data_val_path: ./../data/data_96/val/data_val_chr19_96.npy
INFO: 2023-08-21 13:56:33 Argument device_number: 1
INFO: 2023-08-21 13:56:33 Argument epoch: 1
INFO: 2023-08-21 13:56:33 Argument local_rank: 0
INFO: 2023-08-21 13:56:33 Argument loss: single_channel_no_vgg
INFO: 2023-08-21 13:56:33 Argument max_HiC: 255
INFO: 2023-08-21 13:56:33 Argument num_gpu: 1
INFO: 2023-08-21 13:56:33 Argument num_workers: 1
INFO: 2023-08-21 13:56:33 Argument patch_size: 96
INFO: 2023-08-21 13:56:33 Argument resume_epoch: 0
INFO: 2023-08-21 13:56:33 Argument resume_path: None
INFO: 2023-08-21 13:56:33 Argument rgb: False
INFO: 2023-08-21 13:56:33 Argument train_dataset: hic
INFO: 2023-08-21 13:56:33 Argument val_datasets: ['hic']
INFO: 2023-08-21 13:56:38 epoch:0 dataset: 1/17 step: 0/155 time:0.55+2.01 loss_avg:2.2300e-01
INFO: 2023-08-21 13:56:38 epoch:0 dataset: 1/17 step: 1/155 time:0.00+0.83 loss_avg:1.8877e-01
INFO: Training on data_train_chr7_96.npy complete.
INFO: 2023-08-21 13:56:40 epoch:0 dataset: 2/17 step: 0/90 time:0.51+0.89 loss_avg:2.5133e-01
INFO: 2023-08-21 13:56:41 epoch:0 dataset: 2/17 step: 1/90 time:0.00+0.85 loss_avg:2.4228e-01
INFO: Traceback:
INFO: Traceback (most recent call last):
  File "./train_1d.py", line 316, in <module>
    train(model, args)
  File "./train_1d.py", line 204, in train
    evaluate(model, val_data, val_dataset, epoch, step)
  File "./train_1d.py", line 214, in evaluate
    val_save_path = "./../data/data_{}/train_val/{}_{}/norm_{}/batch_{}/epoch_{}/pred_chr19.npy".format(patch_size, loss, patch_size, max_HiC, batch_size, epoch)
NameError: name 'epoch' is not defined

INFO: Sys.exc_info()[2]:
INFO: <traceback object at 0x7f675dcfbb40>
