INFO: Default loss without VGG
INFO: No cutoff
INFO: 2023-08-21 17:18:44 Argument batch_size: 8
INFO: 2023-08-21 17:18:44 Argument code_test: True
INFO: 2023-08-21 17:18:44 Argument data_train_path: ./../data/data_96/train/
INFO: 2023-08-21 17:18:44 Argument data_val_path: ./../data/data_96/val/data_val_chr19_96.npy
INFO: 2023-08-21 17:18:44 Argument device_number: 1
INFO: 2023-08-21 17:18:44 Argument epoch: 1
INFO: 2023-08-21 17:18:44 Argument local_rank: 0
INFO: 2023-08-21 17:18:44 Argument loss: single_channel_no_vgg
INFO: 2023-08-21 17:18:44 Argument max_HiC: 255
INFO: 2023-08-21 17:18:44 Argument num_gpu: 1
INFO: 2023-08-21 17:18:44 Argument num_workers: 1
INFO: 2023-08-21 17:18:44 Argument patch_size: 96
INFO: 2023-08-21 17:18:44 Argument resume_epoch: 0
INFO: 2023-08-21 17:18:44 Argument resume_path: None
INFO: 2023-08-21 17:18:44 Argument rgb: False
INFO: 2023-08-21 17:18:44 Argument train_dataset: hic
INFO: 2023-08-21 17:18:44 Argument val_datasets: ['hic']
INFO: 2023-08-21 17:18:48 epoch:0 dataset: 1/17 step: 0/155 time:0.55+2.05 loss_avg:2.2300e-01
INFO: 2023-08-21 17:18:49 epoch:0 dataset: 1/17 step: 1/155 time:0.00+0.83 loss_avg:1.8877e-01
INFO: Training on data_train_chr7_96.npy complete.
INFO: 2023-08-21 17:18:50 epoch:0 dataset: 2/17 step: 0/90 time:0.53+0.89 loss_avg:2.5133e-01
INFO: 2023-08-21 17:18:51 epoch:0 dataset: 2/17 step: 1/90 time:0.00+0.80 loss_avg:2.4228e-01
INFO: Traceback:
INFO: Traceback (most recent call last):
  File "./train_1d.py", line 332, in <module>
    train(model, args)
  File "./train_1d.py", line 207, in train
    evaluate(model, data_val_path, val_dataset, epoch, step)
  File "./train_1d.py", line 237, in evaluate
    scores = get_hicrep(patch_size, max_hic, epoch, batch_size, loss, 400000, True, val_save_path + "pred_chr19_final.npy")
NameError: name 'get_hicrep' is not defined

INFO: Sys.exc_info()[2]:
INFO: <traceback object at 0x7fd0ec298c80>
